# Generated by Django 3.1.4 on 2020-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('teaser_image_url', models.CharField(max_length=2000)),
                ('banner_image_url', models.CharField(max_length=2000)),
            ],
        ),
    ]
