# Generated by Django 3.1.4 on 2020-12-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201222_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer_id',
            new_name='writer',
        ),
    ]
